server:
  port: 8081

spring:
  application:
    name: order-service

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  circuitbreaker:
    enabled: true

resilience4fj:
  circuitbreaker:
    instances:
      orderService:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
  retry:
    instances:
      orderServiceRetry:
        maxAttempts: 3
        waitDuration: 500ms
